Feat api_ru.md
amperka/TroykaHatPython pull request #1
Opened 2021-06-22 01:44 UTC by igor605ds

Создал API_ru.md.

Жду правок и пожеланий.

2021-06-22 08:02 UTC, igor605ds commented
Методы и функции в стиле camelCase, для совместимости с либой WiringPI.

2021-06-22 09:22 UTC, nkrkv requested changes

2021-06-22 09:22 UTC, nkrkv commented on API_ru.md
> +_Вся документация ниже относится к объекту `analog_io`._
Нифига не понятно.

> class TroykaHat

... ага, сейчас мне расскажут про класс TroykaHat ...

> Плата расширения Troyka HAT включает в себя две группы контактов: Wiring Pi IO и Analog IO

:exploding_head: 

Нужно так:

```markdown
class TroykaHat

Предоставляет доступ к GPIO-пинам платы TroykaHat. Для создания экземпляра класса используйте методы класса `wiringpi_io` или `analog_io` в зависимости от того, к какой группе пинов будете обращаться.

### @classmethod wiringpi_io -> TroykaHat

Создает новый объект `wiringpi_io` для работы с пинами помеченными на плате как «Wiring Pi IO» на плате Troyka HAT. Это пины подключенные напрямую к компьютеру Raspberry Pi через её GPIO-разъём.

### @classmethod analog_io(i2c_address: int=42) -> TroykaHat

...
```

2021-06-22 09:22 UTC, nkrkv commented on API_ru.md
> +
PinMode со своими возможными значениями должен быть задокументирован отдельно, над классом TroykaHat. А тут не нужно повторяться

2021-06-22 09:22 UTC, nkrkv commented on API_ru.md
> +Возвращаемое значение `True` — высокий уровень или `False` — низкий уровень. Для работы текущей функции пин должен быть сконфигурирован в режим входа в методе `pinMode`.
Что такое «текущая функция»? Что такое «имя пина»?

2021-06-22 09:22 UTC, nkrkv commented on API_ru.md
> +Возвращаемое значение от `0.0` до `1.0` в зависимости от состояния напряжения на пине. Для работы текущей функции пин должен быть сконфигурирован в режим входа в методе `pinMode`.
Какому напряжению соответствует значение `1.0`?

2021-06-22 09:22 UTC, nkrkv commented on API_ru.md
> +- `value`: Значение от `0.0` до `1.0`, которое прямо пропорционально напряжению.
Напряжению чего? Видимо, имеется в виду скважность ШИМ.

2021-06-22 15:42 UTC, igor605ds reviewed
Принял соответствующие правки.

2021-06-22 15:42 UTC, nomad605dis commented on API_ru.md
> +_Вся документация ниже относится к объекту `analog_io`._
Done

2021-06-22 15:42 UTC, nomad605dis commented on API_ru.md
> +Возвращаемое значение `True` — высокий уровень или `False` — низкий уровень. Для работы текущей функции пин должен быть сконфигурирован в режим входа в методе `pinMode`.
Done

2021-06-22 15:42 UTC, nomad605dis commented on API_ru.md
> +Возвращаемое значение от `0.0` до `1.0` в зависимости от состояния напряжения на пине. Для работы текущей функции пин должен быть сконфигурирован в режим входа в методе `pinMode`.
Done

2021-06-22 15:42 UTC, nomad605dis commented on API_ru.md
> +- `value`: Значение от `0.0` до `1.0`, которое прямо пропорционально напряжению.
Done. Можно конечно расшифровать что такое ШИМ, и что мы при определенной нагрузке получаем сразу результирующее выходное напряжение от 0 до 3,3 В. Но вопрос, нужно ли каждый раз про это говорить...

2021-06-22 15:43 UTC, nomad605dis commented on API_ru.md
> +
Done

2021-06-22 20:04 UTC, AlexErAmp requested changes

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Описывает режимы работы пинов ввода вывода.
```suggestion
Описывает режимы работы пинов ввода-вывода.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Создает новый объект `wiringpi_io` для работы с пинами помеченными на плате как «Wiring Pi IO» на плате Troyka HAT. Это пины подключенные напрямую к компьютеру Raspberry Pi через её GPIO-разъём.
```suggestion
Создает новый объект `wiringpi_io` для работы с пинами, помеченными как «Wiring Pi IO» на плате Troyka HAT. Это пины, подключенные напрямую к компьютеру Raspberry Pi через его GPIO-разъём.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Создает новый объект `analog_io` для работы с пинами помеченными на плате как «Analog IO» на плате Troyka HAT. Это пины подключенные к встроенному на плате I²C расширителю на микроконтроллере STM32F0
```suggestion
Создает новый объект `analog_io` для работы с пинами, помеченными как «Analog IO» на плате Troyka HAT. Это пины, подключенные к встроенному на плате I²C расширителю на микроконтроллере STM32F030F4P6.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмеченный на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмеченный на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмеченный на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмеченный на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмеченный на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Для работы текущей функции пин должен быть сконфигурирован в режим выхода в методе `pinMode`.
Опять "текущая функция")

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Сохраняет текущий I²C-адрес устройства в EEPROM, который заранее изменен с помощью метода `changeAddress`.
```suggestion
Сохраняет I²C-адрес устройства, который изменён с помощью метода `changeAddress`, в EEPROM.
```

2021-06-22 20:04 UTC, AlexErAmp commented on API_ru.md
> +Изменяет текущий I²C-адрес модуля.
Я бы убрал, но тут up to you
```suggestion
Изменяет I²C-адрес модуля.
```

2021-06-23 07:12 UTC, igor605ds reviewed
Внёс правки от @AlexErAmp

2021-06-23 07:12 UTC, igor605ds commented on API_ru.md
> +Для работы текущей функции пин должен быть сконфигурирован в режим выхода в методе `pinMode`.
Не заметил, спасибо)

2021-06-23 07:12 UTC, igor605ds commented on API_ru.md
> +Изменяет текущий I²C-адрес модуля.
В принципе ты прав. Это оверкил наверное, два HAT все равно не оденешь.

2021-06-23 07:12 UTC, igor605ds commented on API_ru.md
> +Для работы текущей функции пин должен быть сконфигурирован в режим выхода в методе `pinMode`.
Done

2021-06-23 11:03 UTC, nkrkv requested changes

2021-06-23 11:03 UTC, nkrkv commented on API_ru.md
> +### `@classmethod wiringpi_io -> TroykaHat`
```suggestion
### `@classmethod wiringpi_io() -> TroykaHat`
```

Так-так. А этот метод точно возвращает экземпляр `TroykaHat`? Что выведет `print(type(TroykaHat.wiringpi_io))`? Что-то мне подсказывает, что это будет объект типа определённого в WiringPi, а не наш. Если так, то тут фактическая ошибка. И если так, то нафиг они вообще методы класса? Могут быть просто функциями-конструкторами уровня модуля.

2021-06-23 11:03 UTC, nkrkv commented on API_ru.md
> +_Подробности коммуникации читайте в [документации на библиотеку WiringPi](https://pypi.org/project/wiringpi/)._
```suggestion
_Подробности о коммуникации читайте в [документации на библиотеку WiringPi](https://pypi.org/project/wiringpi/)._
```

2021-06-23 11:03 UTC, nkrkv commented on API_ru.md
> +Используемый пин должен быть сконфигурирован в режим входа в методе `pinMode`.
```suggestion
Используемый пин должен быть предварительно сконфигурирован в режим входа с помощью метода `pinMode`.
```

Здесь и далее

2021-06-25 14:42 UTC, Matthew3000 commented
@igor605ds Продолжаем? На ком встряло?

2021-06-25 15:15 UTC, igor605ds commented
@Matthew3000 Встряло на мне, я сейчас активно изучаю Python, так сказать с каждым часом все более понимаю суть. На выходных все будет.

2021-06-28 10:16 UTC, igor605ds reviewed
Внёс правки от @nkrkv

2021-06-28 10:16 UTC, nomad605dis commented on API_ru.md
> +_Подробности коммуникации читайте в [документации на библиотеку WiringPi](https://pypi.org/project/wiringpi/)._
Done

2021-06-28 10:16 UTC, nomad605dis commented on API_ru.md
> +Используемый пин должен быть сконфигурирован в режим входа в методе `pinMode`.
Done

2021-06-28 12:52 UTC, nkrkv approved these changes
LGTM :+1:

2021-06-29 10:04 UTC, nkrkv approved these changes
:+1:

2021-06-29 10:07 UTC, igor605ds commented
@Matthew3000 Всё гуд?)

2021-06-29 10:31 UTC, Matthew3000 requested changes

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `INPUT`: режим входа.
```suggestion
- `INPUT`: режим ввода.
```

Здесь и далее

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +Используемый пин должен быть предварительно сконфигурирован в режим входа с помощью метода `pinMode`.
```suggestion
Используемый пин должен быть предварительно сконфигурирован в режим ввода с помощью метода `pinMode`.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `7` на панели «Analog IO».
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `7` на панели «Analog IO».
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `7` на панели «Analog IO».
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `7` на панели «Analog IO».
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +Используемый пин должен быть предварительно сконфигурирован в режим выхода с помощью метода `pinMode`.
```suggestion
Используемый пин должен быть предварительно сконфигурирован в режим вывода с помощью метода `pinMode`.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `INPUT_PULLUP`: режим входа с подтяжкой к питанию.
```suggestion
- `INPUT_PULLUP`: режим ввода с подтяжкой к питанию.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `INPUT_PULLDOWN`: режим входа с подтяжкой к земле.
```suggestion
- `INPUT_PULLDOWN`: режим ввода с подтяжкой к земле.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `OUTPUT`: режим выхода.
```suggestion
- `OUTPUT`: режим вывода.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +Используемый пин должен быть предварительно сконфигурирован в режим входа с помощью метода `pinMode`.
```suggestion
Используемый пин должен быть предварительно сконфигурирован в режим ввода с помощью метода `pinMode`.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
```suggestion
- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `7` на панели «Analog IO».
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +Используемый пин должен быть предварительно сконфигурирован в режим выхода с помощью метода `pinMode`.
```suggestion
Используемый пин должен быть предварительно сконфигурирован в режим вывода с помощью метода `pinMode`.
```

2021-06-29 10:31 UTC, Matthew3000 commented on API_ru.md
> +Сохраняет I²C-адрес устройства в EEPROM, который заранее изменен с помощью метода `changeAddress`.
```suggestion
Сохраняет в EEPROM I²C-адрес устройства, который заранее изменен с помощью метода `changeAddress`.
```

2021-06-29 13:18 UTC, igor605ds reviewed
@Matthew3000 Правки принял.
Только вот почему ты предлагаешь изменить:

- вход на ввод
- выход на вывод

2021-06-29 13:18 UTC, nomad605dis commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
Done

2021-06-29 13:18 UTC, nomad605dis commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
Done

2021-06-29 13:18 UTC, nomad605dis commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
Done

2021-06-29 13:18 UTC, nomad605dis commented on API_ru.md
> +Сохраняет I²C-адрес устройства в EEPROM, который заранее изменен с помощью метода `changeAddress`.
Done

2021-06-29 13:18 UTC, nomad605dis commented on API_ru.md
> +- `pin`: номер используемого контакта, который отмечен на плате Troyka HAT индексом от `0` до `9`.
Done

2021-06-29 14:31 UTC, Matthew3000 commented
> @Matthew3000 Правки принял.
> Только вот почему ты предлагаешь изменить:
> 
> * вход на ввод
> * выход на вывод
> 
> На мой взгляд вход и выход более уместны, чем ввод и вывод.
> 
> 1. В комментарии к коду мы всегда пишем: пин в режим входа или пин в режим выхода.
> 2. В статьях у DI HALT тоже режим входа и выхода:
>    http://easyelectronics.ru/avr-uchebnyj-kurs-ustrojstvo-i-rabota-portov-vvoda-vyvoda.html

Не обращал раньше внимания, если честно)
Мне кажется, что если порты/пины называются «ввода-вывода», то и режимы у них «ввод» и «вывод». Input и output так и переводятся. Полностью же фраза как звучит? «Поставить пин в режим ввода/входа данных» или «сигнала». «Вход/выход данных» и «вход/выход сигнала» звучат совершенно не по-русски.

@nkrkv как пишем?

2021-06-29 14:43 UTC, nkrkv commented
Давайте вход и выход. Будем консистентны по отношению к себе, Дихалту и [Википедии](https://ru.wikipedia.org/wiki/GPIO)

2021-06-29 15:08 UTC, igor605ds commented on API_ru.md
> +- `INPUT`: режим входа.
Отменяем

2021-06-29 15:10 UTC, igor605ds commented
@Matthew3000 Закинул правки, кроме  изменений:

- вход -> ввод 
- выход -> вывода

2021-06-29 15:21 UTC, Matthew3000 approved these changes
LGTM

2021-06-29 15:23 UTC, merged