Add troykahat package
amperka/TroykaHatPython pull request #2
Opened 2021-07-09 13:33 UTC by igor605ds

Пока в примере, только blink.

Позже добавлю остальные.

2021-07-09 20:55 UTC, AlexErAmp requested changes

2021-07-09 20:55 UTC, AlexErAmp commented on example/blink.py
> +# Gives access to all the functions of GPIO, which it is marked Analog IO.
```suggestion
# Gives access to all the functions of GPIO, which are marked Analog IO.
```

2021-07-09 20:55 UTC, AlexErAmp commented on example/blink.py
> +# Gives access to all the functions of GPIO, which It is marked Wiring PI IO.
```suggestion
# Gives access to all the functions of GPIO, which are marked Wiring PI IO. 
```

2021-07-09 20:55 UTC, AlexErAmp commented on example/blink.py
> +
Не нужен ли здесь вызов `wp.wiringPiSetup()`? Я конечно понимаю, что он содержится в конструкторе `GpioExpander`, который вызывается далее в функции `analog_io` и поэтому все ок. Но что если пользователь захочет переписать пример, используя только wiringpi? У него ничего не заработает и он даже не поймет почему. Получается нужно либо добавить вызов `wp.wiringPiSetup()` в функцию `wiringpi_io()`, либо как ты предлагал сделать отдельный метод `init()`.

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +    Writes an analog value (PWM wave) to a pin. The pin will generate a steady square wave of the specified duty cycle.
Слишком длинные комментарии. Длина строк комментариев согласно PEP8 равна 72 символам.
См. https://realpython.com/python-pep8/#comments, https://www.python.org/dev/peps/pep-0008/#maximum-line-length
Прогони весь код через Python Black. Также можешь пользоваться flake8.

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +        data = self._reverse_uint16(0x0001 << pin)
```suggestion
        data = self._reverse_uint16(1 << pin)
```

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +        mask = 0x0001 << pin
```suggestion
        mask = 1 << pin
```

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +        data = self._reverse_uint16(0x0001 << pin)
```suggestion
        data = self._reverse_uint16(1 << pin)
```

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +commands = GpioExpanderCommands
Я бы не делал отдельный класс для команд, а сделал бы команды переменными класса `GpioExpander`. @nkrkv , как лучше?

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +from pin import State, Mode
`State` не используется нигде в файле gpio_expander.py. Зачем импортить?

2021-07-09 20:55 UTC, AlexErAmp commented on troykahat/troykahat.py
> +def wiringpi_io():
Неплохо было бы для публичных функций написать docstrings.

2021-07-09 20:55 UTC, AlexErAmp commented on example/blink.py
> +from pin import State, Mode
Это работает? По-моему должно быть `from troykahat import State, Mode`

2021-07-11 18:51 UTC, igor605ds reviewed
@AlexErAmp Внёс твои правки. По некоторым правкам есть вопросы.

2021-07-11 18:51 UTC, nomad605dis commented on example/blink.py
> +from pin import State, Mode
Да, работает. Ведь класс `State` и `Mode` описаны в файле `pin.py`, а не в `troykahat`.

Вот что отвечает Python на твою строку:
```
Traceback (most recent call last):
  File "blink.py", line 2, in <module>
    from troykahat import State, Mode
ImportError: cannot import name 'State' from 'troykahat' (/home/pi/TroykaHatPython/troykahat/troykahat.py)
```

2021-07-11 18:51 UTC, nomad605dis commented on example/blink.py
> +# Gives access to all the functions of GPIO, which It is marked Wiring PI IO.
Done

2021-07-11 18:51 UTC, nomad605dis commented on example/blink.py
> +# Gives access to all the functions of GPIO, which it is marked Analog IO.
Done

2021-07-11 18:51 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +from pin import State, Mode
Done

2021-07-11 18:51 UTC, nomad605dis commented on example/blink.py
> +
Верно, я не заметил, спасибо!
Сейчас выбрал первый вариант: добавил вызов `wiringpi.wiringPiSetup()` в функцию `wiringpi_io()`.
@nkrkv Как считаешь? Или лучше сделать отдельную функцию `init` в модуле `troykahat`?
@AlexErAmp Может надо создать по отдельному примеру `blink` для `analog_io` и `wiringpi_io`?

2021-07-11 18:51 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +        mask = 0x0001 << pin
Done

2021-07-11 18:51 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +        data = self._reverse_uint16(0x0001 << pin)
Done

2021-07-11 18:51 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +    Writes an analog value (PWM wave) to a pin. The pin will generate a steady square wave of the specified duty cycle.
Прогнал весь код через форматер `black` и линтер `flake8`

2021-07-11 18:51 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +        data = self._reverse_uint16(0x0001 << pin)
Done

2021-07-11 18:51 UTC, igor605ds commented on troykahat/troykahat.py
> +def wiringpi_io():
@AlexErAmp Добавил docstrings для двух публичных функций в модуле troykahat.

@nkrkv Мы пишем API.md и docstrings одновременно? Я так понимаю, что docsrings это прям true для Python, а API.md больше для того что бы обсудить реализацию до разработки?

2021-07-12 10:29 UTC, nkrkv requested changes
Тепло :)

2021-07-12 10:29 UTC, nkrkv commented on example/blink.py
> +from pin import State, Mode
Это работает, но оно запутанно и неидиоматично. В стейтменте

```python
from foo.bar.baz import qux
```

`foo` всегда должно быть именем используемого пакета/библиотеки. Поэтому текущий пример стоит переписать в:

```python
from troykahat.pin import State, Mode
```

В целом, вот эта вся группировка по модулям малюсенькой либы тоже удобства не привносит. Я предлагаю или прям вмазать модуль `pin.py` в `__init__.py` или хотябы оттуда его реэкспортировать, чтобы можно было импортировать так, как предлагает @AlexErAmp, т.е. `from troykahat import State, Mode`

2021-07-12 10:29 UTC, nkrkv commented on example/blink.py
> +from pin import State, Mode
Хммм… гля на полный путь файла в ошибке, откуда интерпретатор пытается сделать импорт. Это внутренний модуль. Похоже, что ты пробовал не из той директории всё сделать.

В общем, мне кажется всё кроме `gpio_expander.py` нужно собрать в `__init__.py` да и всё

2021-07-12 10:29 UTC, nkrkv commented on troykahat/gpio_expander.py
> +commands = GpioExpanderCommands
Согласен. Лучше все константы задефайнить под `GpioExpander`. Это более идиоматично.

2021-07-12 10:29 UTC, nkrkv commented on troykahat/troykahat.py
> +def wiringpi_io():
Нужны и docstrings и API.md. API.md — это просто удобная штука и для нас (documentation driven development) и для пользователя, чтобы обозрить весь API

2021-07-12 11:33 UTC, AlexErAmp commented on example/blink.py
> +
Мне кажется логично было бы сделать с `wiringpi_io` простой blink - digitalWrite(HIGH), delay, digitalWrite(LOW). А `analog_io` сделать пример analogRead или analogWrite. Ваш кэп:)

2021-07-15 00:31 UTC, igor605ds reviewed
Внёс очередную порцию правок.

2021-07-15 00:31 UTC, nomad605dis commented on troykahat/gpio_expander.py
> +commands = GpioExpanderCommands
Done

2021-07-15 00:31 UTC, nomad605dis commented on example/blink.py
> +from pin import State, Mode
Done

2021-07-15 00:31 UTC, igor605ds commented on troykahat/troykahat.py
> +def wiringpi_io():
Добавил документацию также на класс GpioExpander

2021-07-15 09:17 UTC, nkrkv requested changes

2021-07-15 09:17 UTC, nkrkv commented on example/blink.py
> +    wp.digitalWrite(7, State.HIGH)
А в `API_ru.md` написано:

```
digitalWrite(pin: int, value: bool) -> None
```

Второй аргумент — bool. А тут какой-то `HIGH`… Может этот `State` вообще не нужен из соображений YAGNI? И просто всюду использовать сырые булины.

Если есть возражения, тогда уж и `API_ru.md` нужно изменить. Он не должен противоречить коду.

2021-07-15 10:18 UTC, igor605ds reviewed
Удалил `class State`.

2021-07-15 10:18 UTC, igor605ds commented on example/blink.py
> +    wp.digitalWrite(7, State.HIGH)
Согласен, зачем нам `HIGH` и `LOW`. Будем использовать сырые булины.
Убираю тогда `class State`.
Отразил изменения в примере.

2021-07-15 23:08 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +            True / HIGH / 1 — setting high level.
```suggestion
            True / 1 — setting high level.
```

2021-07-15 23:08 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +            False / LOW / 0 — setting low level.
```suggestion
            False / 0 — setting low level.
```

2021-07-15 23:08 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +GPIO_EXPANDER_UID = 0x00
Мы же вроде хотели константы внутрь класса GpioExpander поместить?

2021-07-15 23:08 UTC, AlexErAmp commented on troykahat/gpio_expander.py
> +                self._io, GPIO_EXPANDER_DIGITAL_WRITE_LOW, data)
Тут наверное можно применить принцип DRY:
```suggestion
            state = (
                GPIO_EXPANDER_DIGITAL_WRITE_HIGH if value else GPIO_EXPANDER_DIGITAL_WRITE_LOW
            )
            self._i2c.writeReg16(self._io, state, data)
```
Имена констант, кстати, очень длинные. Может имеет смысл их уменьшить?

2021-07-16 07:46 UTC, igor605ds reviewed
Принял порцию новых правок от @AlexErAmp

2021-07-16 07:46 UTC, igor605ds commented on troykahat/gpio_expander.py
> +            True / HIGH / 1 — setting high level.
Done

2021-07-16 07:46 UTC, igor605ds commented on troykahat/gpio_expander.py
> +            False / LOW / 0 — setting low level.
Done

2021-07-16 07:46 UTC, igor605ds commented on troykahat/gpio_expander.py
> +GPIO_EXPANDER_UID = 0x00
И правда, а я внутри модуля поместил. Всё исправил.

2021-07-16 07:46 UTC, igor605ds commented on troykahat/gpio_expander.py
> +                self._io, GPIO_EXPANDER_DIGITAL_WRITE_LOW, data)
1. Применил принцип DRY.
2. Т.к. константы теперь в самом классе, их имена удалось сократить.

2021-07-16 10:31 UTC, nkrkv approved these changes
:fire:

2021-07-16 11:30 UTC, AlexErAmp approved these changes
LGTM :+1:

2021-07-16 12:57 UTC, merged