Add examples
amperka/TroykaHatPython pull request #4
Opened 2021-07-20 11:43 UTC by igor605ds

Добавил примеры в библиотеку.

2021-07-20 13:52 UTC, nkrkv approved these changes
:+1:

2021-07-20 13:52 UTC, nkrkv commented on example/toogle_led.py
> +    if (not(wp.digitalRead(PIN_WP_BUTTON))):
```suggestion
    if not wp.digitalRead(PIN_WP_BUTTON):
```

2021-07-20 14:07 UTC, igor605ds reviewed
Внес исправления))

@AlexErAmp @Matthew3000  Будут ещё правки?

2021-07-20 14:07 UTC, igor605ds commented on example/toogle_led.py
> +    if (not(wp.digitalRead(PIN_WP_BUTTON))):
Точно, лишние скобки. Это все наследство от Си)

2021-07-20 14:07 UTC, nkrkv commented on example/toogle_led.py
> +    if not(wp.digitalRead(PIN_WP_BUTTON)):
```suggestion
    if not wp.digitalRead(PIN_WP_BUTTON):
```

2021-07-20 14:10 UTC, Matthew3000 requested changes

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_analog_io.py
> +# See API.md for the functions reference.
```suggestion
# Check API.md for the functions reference.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_analog_io.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
```suggestion
# Gives access to all the functions of GPIO, 
# that are labeled "Analog IO" on the HAT.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_analog_io.py
> +# Configures Pin Led of Analog IO as an output mode.
```suggestion
# Configures the LED pin of Analog IO to an output mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_analog_io.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Analog IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_analog_io.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Analog IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
```suggestion
# Gives access to all the functions of GPIO, that are labeled "Wiring PI IO" on the HAT.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
```suggestion
# Check WiringPI library API (https://github.com/WiringPi/WiringPi-Python)
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
```suggestion
# Gives access to all the functions of GPIO, that are labeled "Analog IO" on the HAT.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# See API.md for the functions reference.
```suggestion
# Check API.md for the functions reference.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
```suggestion
# Configures the LED pin of Wiring PI IO to an output mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Analog IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# Configures Pin Led of Analog IO as an output mode.
```suggestion
# Configures the LED pin of Analog IO as an output mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Analog IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_wiringpi_io.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_wiringpi_io.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
```suggestion
    # Sets HIGH voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
```suggestion
# Configures the LED pin of Wiring PI IO as an output mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +# Configures Pin Button of Wiring PI IO as an input mode.
```suggestion
# Configures Button the pin of Wiring PI IO as an input mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +    # If button is pressed.
```suggestion
    # If the button is pressed.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +    # If button is released.
```suggestion
    # If the button is released.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +        # Sets HIGH voltage level for Pin Led of Wiring PI IO.
```suggestion
        # Sets HIGH voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +        # Sets LOW voltage level for Pin Led of Wiring PI IO.
```suggestion
        # Sets LOW voltage level for the LED pin of Wiring PI IO.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_wiringpi_io.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
```suggestion
Gives access to all the functions of GPIO, that are labeled "Wiring PI IO" on the HAT.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_wiringpi_io.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
```suggestion
# Check WiringPI library API (https://github.com/WiringPi/WiringPi-Python)
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/blink_led_wiringpi_io.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
```suggestion
# Configures the LED pin of Wiring PI IO to an output mode.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
```suggestion
# Gives access to all the functions of GPIO, that are labeled "Wiring PI IO" on the HAT.
```

2021-07-20 14:10 UTC, Matthew3000 commented on example/toogle_led.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
```suggestion
# Check WiringPI library API (https://github.com/WiringPi/WiringPi-Python)
```

2021-07-20 19:31 UTC, AlexErAmp commented on example/dimming_led.py
> +# Configures Pin Led of Analog IO as an output mode.
```suggestion
# Configures the LED pin of Analog IO as an output mode.
```

2021-07-20 19:33 UTC, AlexErAmp commented on example/dimming_led.py
> +# Configures Pin Potentiometer of Analog IO as an input mode.
```suggestion
# Configures the potentiometer pin of Analog IO as an input mode.
```

2021-07-20 22:43 UTC, igor605ds reviewed
Внёс предложенные правки

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_analog_io.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_analog_io.py
> +# See API.md for the functions reference.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_analog_io.py
> +# Configures Pin Led of Analog IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_analog_io.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_analog_io.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# See API.md for the functions reference.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +# Configures Pin Led of Analog IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_multiple.py
> +    # Sets HIGH voltage level for Pin Led of Analog IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_wiringpi_io.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_wiringpi_io.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_wiringpi_io.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_wiringpi_io.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/blink_led_wiringpi_io.py
> +    # Sets HIGH voltage level for Pin Led of Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/dimming_led.py
> +# Configures Pin Led of Analog IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/dimming_led.py
> +# Configures Pin Potentiometer of Analog IO as an input mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +# Gives access to all the functions of GPIO, which are marked Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +# See API for WiringPI (https://github.com/WiringPi/WiringPi-Python) library
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +# Configures Pin Led of Wiring PI IO as an output mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +# Configures Pin Button of Wiring PI IO as an input mode.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +    # If button is pressed.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +    if not(wp.digitalRead(PIN_WP_BUTTON)):
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +        # Sets HIGH voltage level for Pin Led of Wiring PI IO.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +    # If button is released.
Done

2021-07-20 22:43 UTC, igor605ds commented on example/toogle_led.py
> +        # Sets LOW voltage level for Pin Led of Wiring PI IO.
Done

2021-07-21 08:13 UTC, AlexErAmp approved these changes
LGTM

2021-07-21 10:45 UTC, Matthew3000 requested changes
Fix this and if no questions, then merge

2021-07-21 10:45 UTC, Matthew3000 commented on example/blink_led_multiple.py
> +# Check WiringPI library API (https://github.com/WiringPi/WiringPi-Python)
WiringPI or Wiring PI?
Please choose one of them all over the code.

2021-07-21 10:45 UTC, Matthew3000 commented on example/dimming_led.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
```suggestion
# Gives access to all the functions of GPIO, that are labeled "Analog IO" on the HAT.
```

2021-07-21 10:45 UTC, Matthew3000 commented on example/dimming_led.py
> +# Configures the LED pin of Analog IO as an output mode.
```suggestion
# Configures the LED pin of Analog IO to an output mode.
```

2021-07-21 10:45 UTC, Matthew3000 commented on example/dimming_led.py
> +# Configures the potentiometer pin of Analog IO as an input mode.
```suggestion
# Configures the potentiometer pin of Analog IO to an input mode.
```

2021-07-21 10:45 UTC, Matthew3000 commented on example/toogle_led.py
> +# Configures the LED pin of Wiring PI IO as an output mode.
```suggestion
# Configures the LED pin of Wiring PI IO to an output mode.
```

2021-07-21 10:45 UTC, Matthew3000 commented on example/toogle_led.py
> +# Configures Button the pin of Wiring PI IO as an input mode.
```suggestion
# Configures Button the pin of Wiring PI IO to an input mode.
```

2021-07-21 11:25 UTC, igor605ds reviewed
@Matthew3000 Внёс твои пожелания. Про WiringPi ответил в комментарии.

2021-07-21 11:25 UTC, igor605ds commented on example/dimming_led.py
> +# Gives access to all the functions of GPIO, which are marked Analog IO.
Done

2021-07-21 11:25 UTC, igor605ds commented on example/dimming_led.py
> +# Configures the LED pin of Analog IO as an output mode.
Done

2021-07-21 11:25 UTC, igor605ds commented on example/dimming_led.py
> +# Configures the potentiometer pin of Analog IO as an input mode.
Done

2021-07-21 11:25 UTC, igor605ds commented on example/blink_led_multiple.py
> +# Check WiringPI library API (https://github.com/WiringPi/WiringPi-Python)
Библиотека называется `WiringPi`, а контакты на плате отмечены как `Wiring Pi IO`.

Что предлагаешь?

2021-07-21 12:07 UTC, Matthew3000 commented
> Что предлагаешь?

Тогда так оставляем.

2021-07-21 12:08 UTC, Matthew3000 approved these changes
lgtm

2021-07-21 12:12 UTC, igor605ds commented
🎉 🎉 🎉

2021-07-21 12:12 UTC, merged